sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t advkdp/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run advkdp/react-test npm test -- --coverage

after_success:
  - docker build -t advkdp/multi-client ./client
  - docker build -t advkdp/multi-nginx ./nginx
  - docker build -t advkdp/multi-server ./server
  - docker build -t advkdp/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push advkdp/multi-client
  - docker push advkdp/multi-nginx
  - docker push advkdp/multi-server
  - docker push advkdp/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-447873370974
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
